import type { Metadata } from "next";
import "../globals.css";
import Header from "./_components/Header/Header";
import Footer from "./_components/Footer/Footer";
import { CartProvider } from "@/app/CartContext";
import FadeIn from "@/app/_components/FadeIn";
import { UserProvider } from "@/app/UserContext";
export const metadata: Metadata = {
  title: "Next Sport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <CartProvider>
            <Header />
            <FadeIn
              blur={true}
              duration={150}
              easing="ease-out"
              initialOpacity={0}
            >
              {children}
            </FadeIn>
            <Footer />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
