import type { Metadata } from 'next';
import './globals.css';
import Header from './(store)/_components/Header/Header';
import Footer from './(store)/_components/Footer/Footer';
import { CartProvider } from '@/app/CartContext';
import FadeInWrapper from '@/app/_components/FadeInWrapper';

export const metadata: Metadata = {
    title: 'Nigger Sport',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <CartProvider>
                <Header />
                <FadeInWrapper>{children}</FadeInWrapper>
                <Footer />

        </CartProvider>
        </body>
        </html>
    );
}