export const products = [
  {
    id: 1,
    ProductName: "Hiking Jacket",
    ProductPrice: 79.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "clothing",
  },
  {
    id: 2,
    ProductName: "Trail Running Shoes",
    ProductPrice: 129.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "footwear",
  },
  {
    id: 3,
    ProductName: "Waterproof Pants",
    ProductPrice: 59.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "clothing",
  },
  {
    id: 4,
    ProductName: "Thermal Gloves",
    ProductPrice: 19.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "accessories",
  },
  {
    id: 5,
    ProductName: "Camping Hat",
    ProductPrice: 24.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "accessories",
  },
  {
    id: 6,
    ProductName: "Fleece Pullover",
    ProductPrice: 49.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "clothing",
  },
  {
    id: 7,
    ProductName: "Windbreaker",
    ProductPrice: 89.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "clothing",
  },
  {
    id: 8,
    ProductName: "Backpacking Boots",
    ProductPrice: 149.99,
    imgSrc: "/Assets/BaigePuffer.png",
    category: "footwear",
  },
];
